language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: agCUKFnt1a/UIk+EtM+DV3EkLeQQ4bsDKKMQkqbFnOPOKpKiSJIUgv+iHuw5GHeWkvdFEOpZ8JcSuRbqvTjYm0+DndTB+u6PmzDlgPYMF9BdLTlBBsSQ7b6U/L7Kgtb9wa6EOsSoqGWVRljBP9yN8H6wRV/GOhA/zcvbRdEU7/MHdc2VSHo00EfxhXkphTkSfEjD+TOD2r8mU/I59zRoc+YaaafFoHfZzRKhMNqBOi61AWPp+oyGQ5iRMg+kJxLOtFFJpZhgWhk++fVQ0EddipxbBEXOLhPSW3CZSOmEeXZfCvp97qauarGaEemKkSbRVP0OBlBqriOHov/a29pgm4kbd7zm5gd4O40GUuMEt9/txKuPplIZbspyrtEjKy6rZHHTCoIpwle4ZtHE6/ZK0sn2dIdjUgDoP/cpKki75sAczGJnCOHu8CiAEzBl6XoOmIFz4FVCchHWZnkRfAiygtTo+yw46b9dztXTsZYXo2m43a2KW18qP4LwrPaEKlkgUBs7qKUIiuqb8Ej2oRzz7sx1nwjQ8XvIYyQKgFVS9T80kENtyqQ8dbOGySBHNTTZR0FaudY06wGvvs781CRr8qBcZyUZ/E7Ie4wIB4cUoX5Wy8imfAPHAJGy8g0XAokWB90JiUoj94WfFNKheZg6NsLzhIlYVXZ3LgCWUSXfDqI=
  on:
    tags: true
    repo: jeshraghian/snntorch
    python: 3.8
