language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: CLbcZ0yDz143PNTLYIozDIXIiJFG06Z/p/jYbqQW7OP9ZlbOypOmjdUbfRG0ZcmzUFYzremHnTjb5vziOI1UqcFoIV1o281H/X11hWbVGqbyq6Q7cwHpuA8lnPY7dnZscYEFHHzJxSwRj0eNVbvJOz0Bx01K+Ak2FArYIPzYlXx3Mk7mw657wWlw2dArf00AUqKVn05JBjIfh/fHelhQNTv/krWY4Ea872+HeZH56LVVak/THudXkjqtp01znp+/HdT8uZL0xF8Kc/06fLZdl10GRaT6CFuPmQfeOKyxK5hDIO5sClpkOgYBfOSxnaOHngDB6MmSQi6XL3kyzeeCmRpeHEpSldtUGFZ911ks+GQcs9fmK0Zv3Gtqt5Q4CrXii4zd6RiaBP0v+9kagtmW3KT2fwoxwHS/UI5JMIvNC5jlWgrmSjubRs5JN8WgNvt3FgjsQ4eq5jQpWGyp2m0ejRlDHqyeGk+6Gb/VfSl9hQ6RvIeOihssA1uKCBa+y5bLaF0bZGtDpi2MfscYI0XFSyfL8U3e3vXB9QnDbTwMwu9wM6bSc451k0/8wEqS0UZHGaJ9eAW2qCUnDRTEAcVrfjRoTa19UqijfHDIJqlW1XbnwtQLn0k5kRLOU53tTKrn0lM2F+ck3oqIgYtEJ/Zvl2aGUmWNYBaDSOTur6GjjIw=
  on:
    tags: true
    repo: jeshraghian/snntorch
    python: 3.8
